size(12cm);
pair v = (4,1);
pair w = (2,3);
pair origin = (0,0);
dot("$0$", origin, dir(225));
dot("$\mathbf{v} = \langle x_1, y_1 \rangle$", v, dir(-45), red);
dot("$\mathbf{w} = \langle x_2, y_2 \rangle$", w, dir(135), red);
dot("$\mathbf{v} + \mathbf{w} = \langle x_1 + x_2, y_1 + y_2 \rangle$", v+w, dir(90));
label("$x_1y_2-x_2y_1$", (v+w)/2, blue);
fill(origin--v--(v+w)--w--cycle, opacity(0.1)+lightcyan);
draw(origin--v, EndArrow, Margins);
draw(origin--w, EndArrow, Margins);
draw(v--(v+w), EndArrow, Margins);
draw(w--(v+w), EndArrow, Margins);
